FROM node:22-alpine

#Create a app directory
WORKDIR /app

#Install app dependencies
COPY package*.json ./

RUN npm install

#Bundle app(src) source
COPY . .

EXPOSE 5000

CMD ["npm" , "start"]